name: py39waterpix
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0=h8cf3c4a_0
  - affine=2.3.1=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39ha55989b_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.2=py39ha55989b_1
  - black=22.10.0=py39hcbf5309_2
  - blosc=1.21.1=h74325e0_3
  - boost-cpp=1.78.0=h9f4b32c_1
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - brotlipy=0.7.0=py39ha55989b_1005
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.12.7=h5b45459_0
  - cairo=1.16.0=hd694305_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h68f70e3_2
  - cfitsio=4.2.0=h9ebe7e4_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=win_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - contourpy=1.0.6=py39h1f6ef14_0
  - cryptography=38.0.4=py39h58e9bdb_0
  - curl=7.86.0=heaf79c2_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.4=py39h99910a6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - ecdsa=0.18.0=pyhd8ed1ab_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h1537add_0
  - fastapi=0.88.0=pyhd8ed1ab_0
  - fiona=1.8.22=py39h9e0966e_2
  - flit-core=3.8.0=pyhd8ed1ab_0
  - folium=0.13.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py39ha55989b_1
  - freetype=2.12.1=h546665d_1
  - freexl=1.0.6=h67ca5e6_1
  - gdal=3.5.3=py39h34c8707_4
  - geojson=2.5.0=py_0
  - geomet=1.0.0=pyhd8ed1ab_0
  - geopandas=0.12.1=pyhd8ed1ab_1
  - geopandas-base=0.12.1=pyha770c72_1
  - geos=3.11.1=h1537add_0
  - geotiff=1.7.1=h4ffd875_4
  - gettext=0.21.1=h5728263_0
  - gmpy2=2.1.2=py39hfbe484b_1
  - h11=0.14.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.12.2=nompi_h2a0e4a3_100
  - html2text=2020.1.16=py_0
  - icu=70.1=h0e60522_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2022.2.1=h57928b3_19741
  - ipykernel=6.19.2=pyh025b116_0
  - ipython=8.7.0=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_2
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_core=5.1.0=py39hcbf5309_0
  - kealib=1.4.15=hdf81f3a_1
  - kiwisolver=1.4.4=py39h1f6ef14_1
  - krb5=1.19.3=h1176d77_0
  - lcms2=2.14=h90d422f_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=16_win64_mkl
  - libcurl=7.86.0=heaf79c2_1
  - libdeflate=1.14=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.5.3=h055aab9_4
  - libglib=2.74.1=he8f3873_1
  - libhwloc=2.8.0=h039e092_1
  - libiconv=1.17=h8ffe710_0
  - libkml=1.3.0=hf2ab4e4_1015
  - liblapack=3.9.0=16_win64_mkl
  - libnetcdf=4.8.1=nompi_h8c042bf_106
  - libpng=1.6.39=h19919ed_0
  - libpq=14.5=h04fd8be_2
  - librttopo=1.1.0=he22b5cd_12
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=h07bf483_22
  - libsqlite=3.40.0=hcfcfb64_0
  - libssh2=1.10.0=h680486a_3
  - libtiff=4.4.0=h8e97e67_4
  - libwebp-base=1.2.4=h8ffe710_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.3=hc3477c8_0
  - libzip=1.9.2=hfed4ece_1
  - libzlib=1.2.13=hcfcfb64_4
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39ha55989b_2
  - matplotlib-base=3.6.2=py39haf65ace_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - mpc=1.2.1=h54e1faf_0
  - mpfr=4.1.0=h8d14728_1
  - mpir=3.0.0=he025d50_1002
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py39hcbf5309_6
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=2.8.8=pyhd8ed1ab_0
  - numpy=1.23.5=py39hbccbffa_0
  - openjpeg=2.5.0=hc9384bd_1
  - openssl=1.1.1s=hcfcfb64_1
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.5.2=py39h2ba5b7c_0
  - parso=0.8.3=pyhd8ed1ab_0
  - passlib=1.7.4=pyh9f0ad1d_0
  - pathspec=0.10.3=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39h595c93f_3
  - pip=22.2.2=py39haa95532_0
  - pixman=0.40.0=h8ffe710_0
  - platformdirs=2.6.0=pyhd8ed1ab_0
  - poppler=22.11.0=ha6c1112_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.5=h392df6f_2
  - proj=9.1.0=h3863b3b_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.4=py39ha55989b_0
  - psycopg2=2.9.3=py39h68f70e3_1
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.2=py39ha55989b_1
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.4.0=py39h9727d73_2
  - pysocks=1.7.1=pyh0701188_6
  - python=3.9.15=h6244533_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-jose=3.3.0=pyh6c4a22f_1
  - python-multipart=0.0.5=py_0
  - python_abi=3.9=2_cp39
  - pytz=2022.6=pyhd8ed1ab_0
  - pywin32=304=py39h99910a6_2
  - pyzmq=24.0.1=py39hea35a22_1
  - rasterio=1.3.3=py39h128678e_3
  - requests=2.28.1=pyhd8ed1ab_1
  - rsa=4.9=pyhd8ed1ab_0
  - rtree=1.0.1=py39h09fdee3_1
  - scikit-learn=1.1.3=py39h6fe01c0_1
  - scipy=1.9.3=py39hfbf2dce_2
  - sentinelsat=1.1.1=pyhd8ed1ab_0
  - setuptools=65.5.0=py39haa95532_0
  - shapely=1.8.5=py39h7c5f289_2
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hfb803bf_2
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - sqlite=3.40.0=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - starlette=0.22.0=pyhd8ed1ab_0
  - tbb=2021.7.0=h91493d7_1
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.11.3=h5689973_1
  - tk=8.6.12=h8ffe710_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py39ha55989b_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.7.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.0.0=py39ha55989b_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - uvicorn=0.20.0=py39hcbf5309_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.32.31332=h1d6e394_9
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - wincertstore=0.2=py39haa95532_2
  - xerces-c=3.2.4=h63175ca_1
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2022.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.4=h0e60522_1
  - zlib=1.2.13=hcfcfb64_4
  - zstd=1.5.2=h7755175_4
